
import Foundation

enum CityList {
    static let allCities: [City] = [
        City(name: "Cairo", country: "Egypt"),
        City(name: "Alexandria", country: "Egypt"),
        City(name: "Giza", country: "Egypt"),
        City(name: "Luxor", country: "Egypt"),
        City(name: "Aswan", country: "Egypt"),
        City(name: "Sharm El Sheikh", country: "Egypt"),
        City(name: "Hurghada", country: "Egypt"),
        City(name: "Lagos", country: "Nigeria"),
        City(name: "Abuja", country: "Nigeria"),
        City(name: "Accra", country: "Ghana"),
        City(name: "Nairobi", country: "Kenya"),
        City(name: "Mombasa", country: "Kenya"),
        City(name: "Dar es Salaam", country: "Tanzania"),
        City(name: "Addis Ababa", country: "Ethiopia"),
        City(name: "Casablanca", country: "Morocco"),
        City(name: "Marrakech", country: "Morocco"),
        City(name: "Tunis", country: "Tunisia"),
        City(name: "Algiers", country: "Algeria"),
        City(name: "Cape Town", country: "South Africa"),
        City(name: "Johannesburg", country: "South Africa"),
        City(name: "Durban", country: "South Africa"),
        City(name: "Pretoria", country: "South Africa"),
        City(name: "Kigali", country: "Rwanda"),
        City(name: "Kampala", country: "Uganda"),
        City(name: "Dakar", country: "Senegal"),
        City(name: "Abidjan", country: "Ivory Coast"),
        City(name: "Maputo", country: "Mozambique"),
        City(name: "Lusaka", country: "Zambia"),
        City(name: "Harare", country: "Zimbabwe"),
        City(name: "Windhoek", country: "Namibia"),

        City(name: "Dubai", country: "UAE"),
        City(name: "Abu Dhabi", country: "UAE"),
        City(name: "Sharjah", country: "UAE"),
        City(name: "Riyadh", country: "Saudi Arabia"),
        City(name: "Jeddah", country: "Saudi Arabia"),
        City(name: "Medina", country: "Saudi Arabia"),
        City(name: "Mecca", country: "Saudi Arabia"),
        City(name: "Doha", country: "Qatar"),
        City(name: "Kuwait City", country: "Kuwait"),
        City(name: "Muscat", country: "Oman"),
        City(name: "Manama", country: "Bahrain"),
        City(name: "Amman", country: "Jordan"),
        City(name: "Beirut", country: "Lebanon"),
        City(name: "Baghdad", country: "Iraq"),
        City(name: "Tehran", country: "Iran"),
        City(name: "Sana'a", country: "Yemen"),
        City(name: "Aden", country: "Yemen"),

        City(name: "London", country: "United Kingdom"),
        City(name: "Edinburgh", country: "United Kingdom"),
        City(name: "Manchester", country: "United Kingdom"),
        City(name: "Dublin", country: "Ireland"),
        City(name: "Paris", country: "France"),
        City(name: "Marseille", country: "France"),
        City(name: "Lyon", country: "France"),
        City(name: "Nice", country: "France"),
        City(name: "Amsterdam", country: "Netherlands"),
        City(name: "Rotterdam", country: "Netherlands"),
        City(name: "Brussels", country: "Belgium"),
        City(name: "Zurich", country: "Switzerland"),
        City(name: "Geneva", country: "Switzerland"),
        City(name: "Lisbon", country: "Portugal"),
        City(name: "Porto", country: "Portugal"),
        City(name: "Reykjavik", country: "Iceland"),
        City(name: "Luxembourg", country: "Luxembourg"),

        City(name: "Berlin", country: "Germany"),
        City(name: "Munich", country: "Germany"),
        City(name: "Hamburg", country: "Germany"),
        City(name: "Frankfurt", country: "Germany"),
        City(name: "Cologne", country: "Germany"),
        City(name: "Vienna", country: "Austria"),
        City(name: "Prague", country: "Czech Republic"),
        City(name: "Budapest", country: "Hungary"),
        City(name: "Warsaw", country: "Poland"),
        City(name: "Krakow", country: "Poland"),
        City(name: "Bratislava", country: "Slovakia"),
        City(name: "Ljubljana", country: "Slovenia"),

        City(name: "Rome", country: "Italy"),
        City(name: "Milan", country: "Italy"),
        City(name: "Naples", country: "Italy"),
        City(name: "Venice", country: "Italy"),
        City(name: "Florence", country: "Italy"),
        City(name: "Madrid", country: "Spain"),
        City(name: "Barcelona", country: "Spain"),
        City(name: "Seville", country: "Spain"),
        City(name: "Valencia", country: "Spain"),
        City(name: "Athens", country: "Greece"),
        City(name: "Thessaloniki", country: "Greece"),
        City(name: "Istanbul", country: "Turkey"),
        City(name: "Ankara", country: "Turkey"),
        City(name: "Antalya", country: "Turkey"),
        City(name: "Valletta", country: "Malta"),
        City(name: "Nicosia", country: "Cyprus"),

        City(name: "Copenhagen", country: "Denmark"),
        City(name: "Stockholm", country: "Sweden"),
        City(name: "Gothenburg", country: "Sweden"),
        City(name: "Oslo", country: "Norway"),
        City(name: "Helsinki", country: "Finland"),
        City(name: "Tallinn", country: "Estonia"),
        City(name: "Riga", country: "Latvia"),
        City(name: "Vilnius", country: "Lithuania"),

        City(name: "Moscow", country: "Russia"),
        City(name: "Saint Petersburg", country: "Russia"),
        City(name: "Bucharest", country: "Romania"),
        City(name: "Sofia", country: "Bulgaria"),
        City(name: "Belgrade", country: "Serbia"),
        City(name: "Zagreb", country: "Croatia"),
        City(name: "Sarajevo", country: "Bosnia and Herzegovina"),
        City(name: "Podgorica", country: "Montenegro"),
        City(name: "Skopje", country: "North Macedonia"),
        City(name: "Tirana", country: "Albania"),
        City(name: "Pristina", country: "Kosovo"),
        City(name: "Minsk", country: "Belarus"),
        City(name: "Kyiv", country: "Ukraine"),
        City(name: "Chisinau", country: "Moldova"),

        City(name: "Tbilisi", country: "Georgia"),
        City(name: "Yerevan", country: "Armenia"),
        City(name: "Baku", country: "Azerbaijan"),
        City(name: "Tashkent", country: "Uzbekistan"),
        City(name: "Almaty", country: "Kazakhstan"),
        City(name: "Astana", country: "Kazakhstan"),
        City(name: "Bishkek", country: "Kyrgyzstan"),
        City(name: "Dushanbe", country: "Tajikistan"),
        City(name: "Ashgabat", country: "Turkmenistan"),

        City(name: "Mumbai", country: "India"),
        City(name: "Delhi", country: "India"),
        City(name: "Bangalore", country: "India"),
        City(name: "Chennai", country: "India"),
        City(name: "Kolkata", country: "India"),
        City(name: "Hyderabad", country: "India"),
        City(name: "Islamabad", country: "Pakistan"),
        City(name: "Karachi", country: "Pakistan"),
        City(name: "Lahore", country: "Pakistan"),
        City(name: "Dhaka", country: "Bangladesh"),
        City(name: "Colombo", country: "Sri Lanka"),
        City(name: "Kathmandu", country: "Nepal"),
        City(name: "Kabul", country: "Afghanistan"),

        City(name: "Beijing", country: "China"),
        City(name: "Shanghai", country: "China"),
        City(name: "Guangzhou", country: "China"),
        City(name: "Shenzhen", country: "China"),
        City(name: "Chengdu", country: "China"),
        City(name: "Wuhan", country: "China"),
        City(name: "Hangzhou", country: "China"),
        City(name: "Nanjing", country: "China"),
        City(name: "Chongqing", country: "China"),
        City(name: "Xi'an", country: "China"),
        City(name: "Hong Kong", country: "China"),
        City(name: "Tokyo", country: "Japan"),
        City(name: "Osaka", country: "Japan"),
        City(name: "Nagoya", country: "Japan"),
        City(name: "Sapporo", country: "Japan"),
        City(name: "Kyoto", country: "Japan"),
        City(name: "Seoul", country: "South Korea"),
        City(name: "Busan", country: "South Korea"),
        City(name: "Taipei", country: "Taiwan"),
        City(name: "Ulaanbaatar", country: "Mongolia"),

        City(name: "Bangkok", country: "Thailand"),
        City(name: "Singapore", country: "Singapore"),
        City(name: "Jakarta", country: "Indonesia"),
        City(name: "Bali", country: "Indonesia"),
        City(name: "Manila", country: "Philippines"),
        City(name: "Kuala Lumpur", country: "Malaysia"),
        City(name: "Hanoi", country: "Vietnam"),
        City(name: "Ho Chi Minh City", country: "Vietnam"),
        City(name: "Phnom Penh", country: "Cambodia"),
        City(name: "Yangon", country: "Myanmar"),
        City(name: "Vientiane", country: "Laos"),

        City(name: "New York", country: "United States"),
        City(name: "Los Angeles", country: "United States"),
        City(name: "Chicago", country: "United States"),
        City(name: "San Francisco", country: "United States"),
        City(name: "Miami", country: "United States"),
        City(name: "Houston", country: "United States"),
        City(name: "Boston", country: "United States"),
        City(name: "Seattle", country: "United States"),
        City(name: "Washington DC", country: "United States"),
        City(name: "Philadelphia", country: "United States"),
        City(name: "Dallas", country: "United States"),
        City(name: "Atlanta", country: "United States"),
        City(name: "Denver", country: "United States"),
        City(name: "Las Vegas", country: "United States"),
        City(name: "Portland", country: "United States"),
        City(name: "Phoenix", country: "United States"),
        City(name: "San Diego", country: "United States"),
        City(name: "Austin", country: "United States"),
        City(name: "Honolulu", country: "United States"),
        City(name: "Anchorage", country: "United States"),
        City(name: "Toronto", country: "Canada"),
        City(name: "Vancouver", country: "Canada"),
        City(name: "Montreal", country: "Canada"),
        City(name: "Calgary", country: "Canada"),
        City(name: "Ottawa", country: "Canada"),
        City(name: "Mexico City", country: "Mexico"),
        City(name: "Cancun", country: "Mexico"),
        City(name: "Guadalajara", country: "Mexico"),

        City(name: "Havana", country: "Cuba"),
        City(name: "Panama City", country: "Panama"),
        City(name: "San Jose", country: "Costa Rica"),
        City(name: "Guatemala City", country: "Guatemala"),
        City(name: "Tegucigalpa", country: "Honduras"),
        City(name: "San Salvador", country: "El Salvador"),
        City(name: "Managua", country: "Nicaragua"),
        City(name: "Kingston", country: "Jamaica"),
        City(name: "Port-au-Prince", country: "Haiti"),
        City(name: "Santo Domingo", country: "Dominican Republic"),
        City(name: "Nassau", country: "Bahamas"),

        City(name: "Bogota", country: "Colombia"),
        City(name: "Medellin", country: "Colombia"),
        City(name: "Lima", country: "Peru"),
        City(name: "Santiago", country: "Chile"),
        City(name: "Buenos Aires", country: "Argentina"),
        City(name: "Montevideo", country: "Uruguay"),
        City(name: "Sao Paulo", country: "Brazil"),
        City(name: "Rio de Janeiro", country: "Brazil"),
        City(name: "Brasilia", country: "Brazil"),
        City(name: "Quito", country: "Ecuador"),
        City(name: "Caracas", country: "Venezuela"),
        City(name: "La Paz", country: "Bolivia"),
        City(name: "Asuncion", country: "Paraguay"),
        City(name: "Georgetown", country: "Guyana"),

        City(name: "Sydney", country: "Australia"),
        City(name: "Melbourne", country: "Australia"),
        City(name: "Brisbane", country: "Australia"),
        City(name: "Perth", country: "Australia"),
        City(name: "Adelaide", country: "Australia"),
        City(name: "Canberra", country: "Australia"),
        City(name: "Auckland", country: "New Zealand"),
        City(name: "Wellington", country: "New Zealand"),
        City(name: "Suva", country: "Fiji"),
    ]
}
